import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';

export const languages = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
];

const translations = {
  en: {
    nav_home: 'Home', nav_crops: 'Crops', nav_market: 'Market', nav_ai: 'AI', nav_menu: 'Menu',
    good_morning: 'Good morning', good_afternoon: 'Good afternoon', good_evening: 'Good evening',
    today_action: "What to do today", weather_today: 'Today’s weather',
    ai_says: 'AI advice', crop_status: 'Crop status', market_tip: 'Market tip',
    scheme_reminder: 'Scheme reminder', continue_last: 'Continue last advice',
    emergency_alert: 'Emergency alert',
    spray: 'Spray', wait: 'Wait', sell: 'Sell', check: 'Check', ask: 'Ask', help: 'Help',
    water: 'Water', harvest: 'Harvest', view_why: 'Why?', view: 'View', do_it: 'Do it', done: 'Done',
    crop_health: 'Health', water_need: 'Water need', disease_risk: 'Disease risk',
    next_action: 'Next action', check_leaf: 'Check leaf', water_now: 'Water now',
    spray_tomorrow: 'Spray tomorrow', harvest_soon: 'Harvest soon', my_crops: 'My crops',
    current_price: 'Mandi price', best_sell: 'Best sell time', suggestion: 'Suggestion',
    nearby_mandi: 'Nearby mandi', trend: 'Trend', buy: 'Buy', hold: 'Hold',
    ask_anything: 'Ask me anything…', voice: 'Voice', photo: 'Photo',
    quick_suggestions: 'Quick ask', problem: 'Problem', reason: 'Reason', action: 'Action',
    confidence: 'Confidence', help_scheme: 'Scheme help', send: 'Send', listening: 'Listening…',
    village_status: 'Village status', verified_advisories: 'Verified advisories',
    reports: 'Reports', analytics: 'Analytics', offline_downloads: 'Offline downloads',
    settings: 'Settings', about: 'About', notifications: 'Notifications',
    profile: 'Profile', language: 'Language', offline_mode: 'Offline mode',
    senior_mode: 'Senior-friendly mode',
    urgent: 'Urgent', weather: 'Weather', government: 'Government',
    online: 'Online', offline: 'Offline', last_synced: 'Last synced', cached_advice: 'Cached advice ready',
    high: 'High', medium: 'Medium', low: 'Low', now: 'now', today: 'today',
    enabled: 'On', disabled: 'Off', open: 'Open', close: 'Close', tap_to_speak: 'Tap to speak',
    search_language: 'Search language', sign_out: 'Sign out', dark: 'Dark', light: 'Light',
    farm_assistant: 'Your farm assistant',
    farms: 'My farms',
  },
  hi: {
    nav_home: 'होम', nav_crops: 'फसल', nav_market: 'मंडी', nav_ai: 'एआई', nav_menu: 'मेन्यू',
    good_morning: 'सुप्रभात', good_afternoon: 'नमस्कार', good_evening: 'शुभ संध्या',
    today_action: 'आज क्या करें', weather_today: 'आज का मौसम',
    ai_says: 'एआई सलाह', crop_status: 'फसल स्थिति', market_tip: 'मंडी सुझाव',
    scheme_reminder: 'योजना अनुस्मारक', continue_last: 'पिछली सलाह जारी रखें',
    emergency_alert: 'आपातकालीन सूचना',
    spray: 'छिड़काव', wait: 'रुकें', sell: 'बेचें', check: 'जांचें', ask: 'पूछें', help: 'सहायता',
    water: 'सिंचाई', harvest: 'कटाई', view_why: 'क्यों?', view: 'देखें', do_it: 'करें', done: 'पूर्ण',
    crop_health: 'स्वास्थ्य', water_need: 'पानी', disease_risk: 'बीमारी जोखिम',
    next_action: 'अगला कदम', check_leaf: 'पत्ती जांचें', water_now: 'अभी पानी दें',
    spray_tomorrow: 'कल छिड़काव', harvest_soon: 'जल्द कटाई', my_crops: 'मेरी फसलें',
    current_price: 'मंडी भाव', best_sell: 'बेचने का समय', suggestion: 'सुझाव',
    nearby_mandi: 'नजदीकी मंडी', trend: 'रुझान', buy: 'खरीदें', hold: 'रोकें',
    ask_anything: 'कुछ भी पूछें…', voice: 'आवाज़', photo: 'फोटो',
    quick_suggestions: 'त्वरित पूछें', problem: 'समस्या', reason: 'कारण', action: 'कदम',
    confidence: 'विश्वास', help_scheme: 'योजना सहायता', send: 'भेजें', listening: 'सुन रहा हूँ…',
    village_status: 'गांव स्थिति', verified_advisories: 'सत्यापित सलाह',
    reports: 'रिपोर्ट', analytics: 'विश्लेषण', offline_downloads: 'ऑफलाइन डाउनलोड',
    settings: 'सेटिंग्स', about: 'परिचय', notifications: 'सूचनाएँ',
    profile: 'प्रोफ़ाइल', language: 'भाषा', offline_mode: 'ऑफलाइन मोड',
    senior_mode: 'वरिष्ठ-अनुकूल मोड',
    urgent: 'जरूरी', weather: 'मौसम', government: 'सरकार',
    online: 'ऑनलाइन', offline: 'ऑफलाइन', last_synced: 'अंतिम सिंक', cached_advice: 'कैश सलाह तैयार',
    high: 'अधिक', medium: 'मध्यम', low: 'कम', now: 'अभी', today: 'आज',
    enabled: 'चालू', disabled: 'बंद', open: 'खोलें', close: 'बंद करें', tap_to_speak: 'बोलने के लिए टैप करें',
    search_language: 'भाषा खोजें', sign_out: 'साइन आउट', dark: 'डार्क', light: 'लाइट',
    farm_assistant: 'आपका किसान सहायक',
    farms: 'मेरे फार्म',
  },
  mr: {
    nav_home: 'होम', nav_crops: 'पीक', nav_market: 'बाजार', nav_ai: 'एआय', nav_menu: 'मेन्यू',
    good_morning: 'सुप्रभात', good_afternoon: 'नमस्कार', good_evening: 'शुभ संध्या',
    today_action: 'आज काय करायचे', weather_today: 'आजचे हवामान',
    ai_says: 'एआय सल्ला', crop_status: 'पीक स्थिती', market_tip: 'बाजार सल्ला',
    scheme_reminder: 'योजना आठवण', continue_last: 'मागील सल्ला सुरू ठेवा',
    emergency_alert: 'आपत्कालीन सूचना',
    spray: 'फवारणी', wait: 'थांबा', sell: 'विका', check: 'तपासा', ask: 'विचारा', help: 'मदत',
    water: 'पाणी', harvest: 'कापणी', view_why: 'का?', view: 'पहा', do_it: 'करा', done: 'पूर्ण',
    crop_health: 'आरोग्य', water_need: 'पाणी गरज', disease_risk: 'रोग जोखीम',
    next_action: 'पुढील पाऊल', check_leaf: 'पान तपासा', water_now: 'आता पाणी द्या',
    spray_tomorrow: 'उद्या फवारणी', harvest_soon: 'लवकर कापणी', my_crops: 'माझी पिके',
    current_price: 'बाजार भाव', best_sell: 'विकण्याची वेळ', suggestion: 'सल्ला',
    nearby_mandi: 'जवळचा बाजार', trend: 'कल', buy: 'विकत घ्या', hold: 'थांबा',
    ask_anything: 'काहीही विचारा…', voice: 'आवाज', photo: 'फोटो',
    quick_suggestions: 'जलद विचारा', problem: 'समस्या', reason: 'कारण', action: 'पाऊल',
    confidence: 'विश्वास', help_scheme: 'योजना मदत', send: 'पाठवा', listening: 'ऐकत आहे…',
    village_status: 'गाव स्थिती', verified_advisories: 'तपासलेले सल्ले',
    reports: 'अहवाल', analytics: 'विश्लेषण', offline_downloads: 'ऑफलाइन डाउनलोड',
    settings: 'सेटिंग्ज', about: 'माहिती', notifications: 'सूचना',
    profile: 'प्रोफाइल', language: 'भाषा', offline_mode: 'ऑफलाइन मोड',
    senior_mode: 'वयोवृद्ध-अनुकूल मोड',
    urgent: 'तातडीचे', weather: 'हवामान', government: 'सरकार',
    online: 'ऑनलाइन', offline: 'ऑफलाइन', last_synced: 'शेवटचा सिंक', cached_advice: 'कॅश सल्ला तयार',
    high: 'जास्त', medium: 'मध्यम', low: 'कमी', now: 'आता', today: 'आज',
    enabled: 'चालू', disabled: 'बंद', open: 'उघडा', close: 'बंद करा', tap_to_speak: 'बोलण्यासाठी टॅप करा',
    search_language: 'भाषा शोधा', sign_out: 'साइन आउट', dark: 'डार्क', light: 'लाइट',
    farm_assistant: 'तुमचा शेतकरी सहाय्यक',
    farms: 'माझे फार्म',
  },
  gu: {
    nav_home: 'હોમ', nav_crops: 'પાક', nav_market: 'બજાર', nav_ai: 'એઆઈ', nav_menu: 'મેનૂ',
    good_morning: 'સુપ્રભાત', good_afternoon: 'નમસ્કાર', good_evening: 'શુભ સાંજ',
    today_action: 'આજે શું કરવું', weather_today: 'આજનું હવામાન',
    ai_says: 'એઆઈ સલાહ', crop_status: 'પાક સ્થિતિ', market_tip: 'બજાર સલાહ',
    scheme_reminder: 'યોજના રીમાઇન્ડર', continue_last: 'છેલ્લી સલાહ ચાલુ રાખો',
    emergency_alert: 'કટોકટી સૂચના',
    spray: 'છંટાકાવ', wait: 'રોકાઓ', sell: 'વેચો', check: 'ચકાસો', ask: 'પૂછો', help: 'મદદ',
    water: 'પાણી', harvest: 'લણણી', view_why: 'શા માટે?', view: 'જુઓ', do_it: 'કરો', done: 'પૂર્ણ',
    crop_health: 'સ્વાસ્થ્ય', water_need: 'પાણી જરૂર', disease_risk: 'રોગ જોખમ',
    next_action: 'આગળનું પગલું', check_leaf: 'પાન ચકાસો', water_now: 'હમણાં પાણી આપો',
    spray_tomorrow: 'કાલે છંટાકાવ', harvest_soon: 'જલ્દી લણણી', my_crops: 'મારા પાક',
    current_price: 'બજાર ભાવ', best_sell: 'વેચવાનો સમય', suggestion: 'સલાહ',
    nearby_mandi: 'નજીકનો બજાર', trend: 'વલણ', buy: 'ખરીદો', hold: 'રોકો',
    ask_anything: 'કંઈપણ પૂછો…', voice: 'અવાજ', photo: 'ફોટો',
    quick_suggestions: 'ઝડપી પૂછો', problem: 'સમસ્યા', reason: 'કારણ', action: 'પગલું',
    confidence: 'વિશ્વાસ', help_scheme: 'યોજના મદદ', send: 'મોકલો', listening: 'સાંભળી રહ્યો છું…',
    village_status: 'ગામ સ્થિતિ', verified_advisories: 'ચકાસાયેલ સલાહ',
    reports: 'અહેવાલ', analytics: 'વિશ્લેષણ', offline_downloads: 'ઑફલાઇન ડાઉનલોડ',
    settings: 'સેટિંગ્સ', about: 'માહિતી', notifications: 'સૂચનાઓ',
    profile: 'પ્રોફાઇલ', language: 'ભાષા', offline_mode: 'ઑફલાઇન મોડ',
    senior_mode: 'વૃદ્ધ-અનુકૂળ મોડ',
    urgent: 'તાકીદ', weather: 'હવામાન', government: 'સરકાર',
    online: 'ઑનલાઇન', offline: 'ઑફલાઇન', last_synced: 'છેલ્લો સિંક', cached_advice: 'કૅશ સલાહ તૈયાર',
    high: 'વધારે', medium: 'મધ્યમ', low: 'ઓછું', now: 'હમણાં', today: 'આજે',
    enabled: 'ચાલુ', disabled: 'બંધ', open: 'ખોલો', close: 'બંધ કરો', tap_to_speak: 'બોલવા માટે ટૅપ કરો',
    search_language: 'ભાષા શોધો', sign_out: 'સાઇન આઉટ', dark: 'ડાર્ક', light: 'લાઇટ',
    farm_assistant: 'તમારો ખેડૂત સહાયક',
    farms: 'મારા ફાર્મ',
  },
  ta: {
    nav_home: 'முகப்பு', nav_crops: 'பயிர்', nav_market: 'சந்தை', nav_ai: 'ஏஐ', nav_menu: 'பட்டி',
    good_morning: 'காலை வணக்கம்', good_afternoon: 'நண்பகல் வணக்கம்', good_evening: 'மாலை வணக்கம்',
    today_action: 'இன்று என்ன செய்ய', weather_today: 'இன்றைய வானிலை',
    ai_says: 'ஏஐ ஆலோசனை', crop_status: 'பயிர் நிலை', market_tip: 'சந்தை ஆலோசனை',
    scheme_reminder: 'திட்ட நினைவூட்டல்', continue_last: 'கடைசி ஆலோசனையை தொடரவும்',
    emergency_alert: 'அவசர அறிவிப்பு',
    spray: 'தெளிக்கவும்', wait: 'பொறுக்கவும்', sell: 'விற்கவும்', check: 'சரிபார்க்கவும்', ask: 'கேளுங்கள்', help: 'உதவி',
    water: 'நீர்', harvest: 'அறுவடை', view_why: 'ஏன்?', view: 'பார்க்கவும்', do_it: 'செய்யவும்', done: 'முடிந்தது',
    crop_health: 'ஆரோக்கியம்', water_need: 'நீர் தேவை', disease_risk: 'நோய் ஆபத்து',
    next_action: 'அடுத்த செயல்', check_leaf: 'இலை சரிபார்க்கவும்', water_now: 'இப்போது நீர் பாய்க்கவும்',
    spray_tomorrow: 'நாளை தெளிக்கவும்', harvest_soon: 'விரைவில் அறுவடை', my_crops: 'என் பயிர்கள்',
    current_price: 'சந்தை விலை', best_sell: 'விற்க சிறந்த நேரம்', suggestion: 'ஆலோசனை',
    nearby_mandi: 'அருகில் சந்தை', trend: 'போக்கு', buy: 'வாங்கவும்', hold: 'பிடிக்கவும்',
    ask_anything: 'எதையும் கேளுங்கள்…', voice: 'குரல்', photo: 'புகைப்படம்',
    quick_suggestions: 'விரைவு கேள்வி', problem: 'பிரச்சினை', reason: 'காரணம்', action: 'செயல்',
    confidence: 'நம்பிக்கை', help_scheme: 'திட்ட உதவி', send: 'அனுப்பவும்', listening: 'கேட்கிறேன்…',
    village_status: 'கிராம நிலை', verified_advisories: 'சரிபார்க்கப்பட்ட ஆலோசனை',
    reports: 'அறிக்கை', analytics: 'பகுப்பாய்வு', offline_downloads: 'ஆஃப்லைன் பதிவிறக்கம்',
    settings: 'அமைப்புகள்', about: 'பற்றி', notifications: 'அறிவிப்புகள்',
    profile: 'சுயவிவரம்', language: 'மொழி', offline_mode: 'ஆஃப்லைன் பயன்முறை',
    senior_mode: 'மூத்தோர்-நட்பு பயன்முறை',
    urgent: 'அவசரம்', weather: 'வானிலை', government: 'அரசு',
    online: 'ஆன்லைன்', offline: 'ஆஃப்லைன்', last_synced: 'கடைசி ஒத்திசைவு', cached_advice: 'தற்காலிக ஆலோசனை தயார்',
    high: 'அதிக', medium: 'நடுத்தர', low: 'குறைவு', now: 'இப்போது', today: 'இன்று',
    enabled: 'இயக்கம்', disabled: 'அணை', open: 'திறக்கவும்', close: 'மூடவும்', tap_to_speak: 'பேச தட்டவும்',
    search_language: 'மொழியைத் தேடவும்', sign_out: 'வெளியேறு', dark: 'டார்க்', light: 'லைட்',
    farm_assistant: 'உங்கள் விவசாய உதவியாளர்',
    farms: 'என் பண்ணைகள்',
  },
  te: {
    nav_home: 'హోమ్', nav_crops: 'పంట', nav_market: 'మార్కెట్', nav_ai: 'ఏఐ', nav_menu: 'మెనూ',
    good_morning: 'శుభోదయం', good_afternoon: 'నమస్కారం', good_evening: 'శుభ సాయంత్రం',
    today_action: 'నేడు ఏమి చేయాలి', weather_today: 'నేటి వాతావరణం',
    ai_says: 'ఏఐ సలహా', crop_status: 'పంట స్థితి', market_tip: 'మార్కెట్ సలహా',
    scheme_reminder: 'పథకం రిమైండర్', continue_last: 'చివరి సలహా కొనసాగించండి',
    emergency_alert: 'అత్యవసర సూచన',
    spray: 'పిచికరించండి', wait: 'ఆగండి', sell: 'అమ్మండి', check: 'తనిఖీ చేయండి', ask: 'అడగండి', help: 'సహాయం',
    water: 'నీరు', harvest: 'పంట కోత', view_why: 'ఎందుకు?', view: 'చూడండి', do_it: 'చేయండి', done: 'పూర్తయింది',
    crop_health: 'ఆరోగ్యం', water_need: 'నీరు అవసరం', disease_risk: 'వ్యాధి ప్రమాదం',
    next_action: 'తదుపరి చర్య', check_leaf: 'ఆకు తనిఖీ', water_now: 'ఇప్పుడే నీరు ఇవ్వండి',
    spray_tomorrow: 'రేపు పిచికరించండి', harvest_soon: 'త్వరలో పంట కోత', my_crops: 'నా పంటలు',
    current_price: 'మార్కెట్ ధర', best_sell: 'అమ్మడానికి ఉత్తమ సమయం', suggestion: 'సలహా',
    nearby_mandi: 'సమీప మార్కెట్', trend: 'ధోరణి', buy: 'కొనండి', hold: 'ఆపండి',
    ask_anything: 'ఏదైనా అడగండి…', voice: 'స్వర', photo: 'ఫోటో',
    quick_suggestions: 'త్వరిత ప్రశ్న', problem: 'సమస్య', reason: 'కారణం', action: 'చర్య',
    confidence: 'విశ్వాసం', help_scheme: 'పథకం సహాయం', send: 'పంపండి', listening: 'వింటోంది…',
    village_status: 'గ్రామ స్థితి', verified_advisories: 'ధృవీకరించిన సలహాలు',
    reports: 'నివేదికలు', analytics: 'విశ్లేషణ', offline_downloads: 'ఆఫ్లైన్ డౌన్లోడ్',
    settings: 'సెట్టింగ్లు', about: 'గురించి', notifications: 'నోటిఫికేషన్లు',
    profile: 'ప్రొఫైల్', language: 'భాష', offline_mode: 'ఆఫ్లైన్ మోడ్',
    senior_mode: 'సీనియర్-అనుకూల మోడ్',
    urgent: 'అత్యవసరం', weather: 'వాతావరణం', government: 'ప్రభుత్వం',
    online: 'ఆన్లైన్', offline: 'ఆఫ్లైన్', last_synced: 'చివరి సింక్', cached_advice: 'కాష్ సలహా సిద్ధం',
    high: 'ఎక్కువ', medium: 'మధ్యమ', low: 'తక్కువ', now: 'ఇప్పుడే', today: 'నేడు',
    enabled: 'ఆన్', disabled: 'ఆఫ్', open: 'తెరవండి', close: 'మూసివేయండి', tap_to_speak: 'మాట్లాడటానికి ట్యాప్ చేయండి',
    search_language: 'భాష శోధించండి', sign_out: 'సైన్ అవుట్', dark: 'డార్క్', light: 'లైట్',
    farm_assistant: 'మీ వ్యవసాయ సహాయకుడు',
    farms: 'నా పొలాలు',
  },
  bn: {
    nav_home: 'হোম', nav_crops: 'ফসল', nav_market: 'বাজার', nav_ai: 'এআই', nav_menu: 'মেনু',
    good_morning: 'সুপ্রভাত', good_afternoon: 'নমস্কার', good_evening: 'শুভ সন্ধ্যা',
    today_action: 'আজ কী করবেন', weather_today: 'আজকের আবহাওয়া',
    ai_says: 'এআই পরামর্শ', crop_status: 'ফসল অবস্থা', market_tip: 'বাজার পরামর্শ',
    scheme_reminder: 'প্রকল্প স্মারক', continue_last: 'শেষ পরামর্শ চালিয়ে যান',
    emergency_alert: 'জরুরি বিজ্ঞপ্তি',
    spray: 'স্প্রে করুন', wait: 'অপেক্ষা করুন', sell: 'বিক্রি করুন', check: 'যাচাই করুন', ask: 'জিজ্ঞাসা করুন', help: 'সাহায্য',
    water: 'জল', harvest: 'ফসল কাটা', view_why: 'কেন?', view: 'দেখুন', do_it: 'করুন', done: 'সম্পন্ন',
    crop_health: 'স্বাস্থ্য', water_need: 'জল প্রয়োজন', disease_risk: 'রোগ ঝুঁকি',
    next_action: 'পরবর্তী পদক্ষেপ', check_leaf: 'পাতা যাচাই করুন', water_now: 'এখনই জল দিন',
    spray_tomorrow: 'আগামীকাল স্প্রে করুন', harvest_soon: 'শীঘ্রই ফসল কাটুন', my_crops: 'আমার ফসল',
    current_price: 'বাজার মূল্য', best_sell: 'বিক্রির সেরা সময়', suggestion: 'পরামর্শ',
    nearby_mandi: 'কাছের বাজার', trend: 'প্রবণতা', buy: 'কিনুন', hold: 'ধরে রাখুন',
    ask_anything: 'কিছু জিজ্ঞাসা করুন…', voice: 'কণ্ঠ', photo: 'ছবি',
    quick_suggestions: 'দ্রুত জিজ্ঞাসা', problem: 'সমস্যা', reason: 'কারণ', action: 'পদক্ষেপ',
    confidence: 'নিশ্চয়তা', help_scheme: 'প্রকল্প সাহায্য', send: 'পাঠান', listening: 'শুনছি…',
    village_status: 'গ্রাম অবস্থা', verified_advisories: 'যাচাইকৃত পরামর্শ',
    reports: 'প্রতিবেদন', analytics: 'বিশ্লেষণ', offline_downloads: 'অফলাইন ডাউনলোড',
    settings: 'সেটিংস', about: 'সম্পর্কে', notifications: 'বিজ্ঞপ্তি',
    profile: 'প্রোফাইল', language: 'ভাষা', offline_mode: 'অফলাইন মোড',
    senior_mode: 'প্রবীণ-বান্ধব মোড',
    urgent: 'জরুরি', weather: 'আবহাওয়া', government: 'সরকার',
    online: 'অনলাইন', offline: 'অফলাইন', last_synced: 'শেষ সিঙ্ক', cached_advice: 'ক্যাশ পরামর্শ প্রস্তুত',
    high: 'বেশি', medium: 'মাঝারি', low: 'কম', now: 'এখন', today: 'আজ',
    enabled: 'চালু', disabled: 'বন্ধ', open: 'খুলুন', close: 'বন্ধ করুন', tap_to_speak: 'কথা বলতে ট্যাপ করুন',
    search_language: 'ভাষা খুঁজুন', sign_out: 'সাইন আউট', dark: 'ডার্ক', light: 'লাইট',
    farm_assistant: 'আপনার কৃষি সহায়ক',
    farms: 'আমার খামার',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = typeof window !== 'undefined' ? window.localStorage.getItem('kisaan_lang') : null;
    return stored && translations[stored] ? stored : 'en';
  });
  useEffect(() => {
    window.localStorage.setItem('kisaan_lang', lang);
  }, [lang]);
  const t = useCallback((key) => translations[lang]?.[key] ?? translations.en[key] ?? key, [lang]);
  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);