"""remove crop from farms

Revision ID: 2e0b04810a4e
Revises: ab1828bcfe70
Create Date: 2026-08-02 21:29:19.050050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0b04810a4e'
down_revision: Union[str, Sequence[str], None] = 'ab1828bcfe70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'crop')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farms', sa.Column('crop', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
